import type { PlanMetadata, PricedAuditTool } from "@/types/audit";

export const pricingMetadata = {
  Claude: [
    {
      tool: "Claude",
      planName: "Free",
      monthlyPrice: 0,
      intendedTeamSize: { min: 1, max: 1 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: true,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Content and marketing", "Data analysis", "Research"],
      codingFocused: false,
      usageIntensity: "light",
      enterpriseFocused: false,
      description:
        "Free individual access for light writing, analysis, coding, web search, and connector usage.",
    },
    {
      tool: "Claude",
      planName: "Pro",
      monthlyPrice: 20,
      intendedTeamSize: { min: 1, max: 4 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: true,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Content and marketing", "Data analysis", "Engineering productivity", "Research", "Mixed usage"],
      codingFocused: false,
      usageIntensity: "standard",
      enterpriseFocused: false,
      description:
        "Individual productivity plan with more usage, Claude Code, projects, Research, and Microsoft connectors.",
    },
    {
      tool: "Claude",
      planName: "Max",
      monthlyPrice: 100,
      intendedTeamSize: { min: 1, max: 2 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: true,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity", "Data analysis", "Research"],
      codingFocused: false,
      usageIntensity: "heavy",
      enterpriseFocused: false,
      description:
        "Higher-usage individual plan for power users who need materially more Claude capacity than Pro.",
    },
    {
      tool: "Claude",
      planName: "Team",
      monthlyPrice: 25,
      intendedTeamSize: { min: 5, max: 150 },
      features: {
        collaboration: true,
        adminControls: true,
        sso: true,
        analytics: false,
        connectors: true,
      },
      security: {
        dataControls: true,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Company-wide AI access", "Engineering productivity", "Data analysis", "Research", "Mixed usage"],
      codingFocused: false,
      usageIntensity: "standard",
      enterpriseFocused: false,
      description:
        "Team plan for 5 to 150 users with central billing, SSO, admin controls, connectors, and enterprise search.",
    },
    {
      tool: "Claude",
      planName: "Enterprise",
      monthlyPrice: 0,
      intendedTeamSize: { min: 150, max: null },
      features: {
        collaboration: true,
        adminControls: true,
        sso: true,
        analytics: true,
        connectors: true,
      },
      security: {
        dataControls: true,
        auditLogs: true,
        scim: true,
        ipIndemnity: false,
        customRetention: true,
      },
      idealUseCases: ["Company-wide AI access", "Product automation"],
      codingFocused: false,
      usageIntensity: "enterprise",
      enterpriseFocused: true,
      description:
        "Custom-priced large-business plan with Team features plus SCIM, audit logs, compliance API, custom retention, and usage controls.",
    },
  ],
  ChatGPT: [
    {
      tool: "ChatGPT",
      planName: "Free",
      monthlyPrice: 0,
      intendedTeamSize: { min: 1, max: 1 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: false,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Content and marketing", "Data analysis", "Research"],
      codingFocused: false,
      usageIntensity: "light",
      enterpriseFocused: false,
      description:
        "Free individual plan with limited access to flagship models and core assistant features.",
    },
    {
      tool: "ChatGPT",
      planName: "Plus",
      monthlyPrice: 20,
      intendedTeamSize: { min: 1, max: 4 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: false,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Content and marketing", "Data analysis", "Engineering productivity", "Research", "Mixed usage"],
      codingFocused: false,
      usageIntensity: "standard",
      enterpriseFocused: false,
      description:
        "Individual paid plan with expanded access, higher limits, deep research, voice, tasks, and custom GPTs.",
    },
    {
      tool: "ChatGPT",
      planName: "Pro",
      monthlyPrice: 200,
      intendedTeamSize: { min: 1, max: 2 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: false,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity", "Data analysis", "Research"],
      codingFocused: false,
      usageIntensity: "heavy",
      enterpriseFocused: false,
      description:
        "High-access individual plan for heavy usage, deep research, advanced models, and early access features.",
    },
    {
      tool: "ChatGPT",
      planName: "Business",
      monthlyPrice: 25,
      intendedTeamSize: { min: 2, max: 250 },
      features: {
        collaboration: true,
        adminControls: true,
        sso: true,
        analytics: false,
        connectors: true,
      },
      security: {
        dataControls: true,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Company-wide AI access", "Product automation", "Data analysis", "Research", "Mixed usage"],
      codingFocused: false,
      usageIntensity: "standard",
      enterpriseFocused: false,
      description:
        "Collaborative workspace with admin controls, SSO/MFA, connectors, data controls, business features, and fixed per-seat billing.",
    },
    {
      tool: "ChatGPT",
      planName: "Enterprise",
      monthlyPrice: 0,
      intendedTeamSize: { min: 250, max: null },
      features: {
        collaboration: true,
        adminControls: true,
        sso: true,
        analytics: true,
        connectors: true,
      },
      security: {
        dataControls: true,
        auditLogs: true,
        scim: true,
        ipIndemnity: false,
        customRetention: true,
      },
      idealUseCases: ["Company-wide AI access", "Product automation"],
      codingFocused: false,
      usageIntensity: "enterprise",
      enterpriseFocused: true,
      description:
        "Custom-priced enterprise workspace with expanded admin, security, analytics, and support controls.",
    },
  ],
  Cursor: [
    {
      tool: "Cursor",
      planName: "Hobby",
      monthlyPrice: 0,
      intendedTeamSize: { min: 1, max: 1 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: false,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity"],
      codingFocused: true,
      usageIntensity: "light",
      enterpriseFocused: false,
      description:
        "Free individual plan with limited agent requests and tab completions.",
    },
    {
      tool: "Cursor",
      planName: "Pro",
      monthlyPrice: 20,
      intendedTeamSize: { min: 1, max: 9 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: false,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity"],
      codingFocused: true,
      usageIntensity: "standard",
      enterpriseFocused: false,
      description:
        "Individual coding plan with extended agent limits, frontier models, MCPs, skills, hooks, and cloud agents.",
    },
    {
      tool: "Cursor",
      planName: "Pro+",
      monthlyPrice: 60,
      intendedTeamSize: { min: 1, max: 5 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: false,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity"],
      codingFocused: true,
      usageIntensity: "heavy",
      enterpriseFocused: false,
      description:
        "Higher-usage individual plan with roughly 3x usage across OpenAI, Claude, and Gemini models.",
    },
    {
      tool: "Cursor",
      planName: "Teams",
      monthlyPrice: 40,
      intendedTeamSize: { min: 5, max: 200 },
      features: {
        collaboration: true,
        adminControls: true,
        sso: true,
        analytics: true,
        connectors: false,
      },
      security: {
        dataControls: true,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity", "Company-wide AI access", "Mixed usage"],
      codingFocused: true,
      usageIntensity: "standard",
      enterpriseFocused: false,
      description:
        "Team coding plan with shared chats, team billing, usage analytics, privacy controls, RBAC, and SSO/OIDC.",
    },
    {
      tool: "Cursor",
      planName: "Enterprise",
      monthlyPrice: 0,
      intendedTeamSize: { min: 200, max: null },
      features: {
        collaboration: true,
        adminControls: true,
        sso: true,
        analytics: true,
        connectors: false,
      },
      security: {
        dataControls: true,
        auditLogs: true,
        scim: true,
        ipIndemnity: false,
        customRetention: true,
      },
      idealUseCases: ["Engineering productivity", "Company-wide AI access", "Mixed usage"],
      codingFocused: true,
      usageIntensity: "enterprise",
      enterpriseFocused: true,
      description:
        "Custom-priced enterprise coding plan with pooled usage, invoice billing, SCIM, audit logs, granular controls, and priority support.",
    },
  ],
  "GitHub Copilot": [
    {
      tool: "GitHub Copilot",
      planName: "Free",
      monthlyPrice: 0,
      intendedTeamSize: { min: 1, max: 1 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: false,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity"],
      codingFocused: true,
      usageIntensity: "light",
      enterpriseFocused: false,
      description:
        "Free individual Copilot access with limited completions and premium requests.",
    },
    {
      tool: "GitHub Copilot",
      planName: "Pro",
      monthlyPrice: 10,
      intendedTeamSize: { min: 1, max: 4 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: false,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity"],
      codingFocused: true,
      usageIntensity: "standard",
      enterpriseFocused: false,
      description:
        "Individual coding plan with unlimited inline suggestions, Copilot Chat, code review, and premium requests.",
    },
    {
      tool: "GitHub Copilot",
      planName: "Pro+",
      monthlyPrice: 39,
      intendedTeamSize: { min: 1, max: 4 },
      features: {
        collaboration: false,
        adminControls: false,
        sso: false,
        analytics: false,
        connectors: false,
      },
      security: {
        dataControls: false,
        auditLogs: false,
        scim: false,
        ipIndemnity: false,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity"],
      codingFocused: true,
      usageIntensity: "heavy",
      enterpriseFocused: false,
      description:
        "Higher-usage individual plan with more premium requests and access to additional frontier models.",
    },
    {
      tool: "GitHub Copilot",
      planName: "Business",
      monthlyPrice: 19,
      intendedTeamSize: { min: 2, max: 500 },
      features: {
        collaboration: true,
        adminControls: true,
        sso: false,
        analytics: true,
        connectors: false,
      },
      security: {
        dataControls: true,
        auditLogs: false,
        scim: false,
        ipIndemnity: true,
        customRetention: false,
      },
      idealUseCases: ["Engineering productivity", "Company-wide AI access"],
      codingFocused: true,
      usageIntensity: "standard",
      enterpriseFocused: false,
      description:
        "Organization plan with seat management, policy controls, business data protections, and per-user billing.",
    },
    {
      tool: "GitHub Copilot",
      planName: "Enterprise",
      monthlyPrice: 39,
      intendedTeamSize: { min: 100, max: null },
      features: {
        collaboration: true,
        adminControls: true,
        sso: true,
        analytics: true,
        connectors: true,
      },
      security: {
        dataControls: true,
        auditLogs: true,
        scim: true,
        ipIndemnity: true,
        customRetention: true,
      },
      idealUseCases: ["Engineering productivity", "Company-wide AI access"],
      codingFocused: true,
      usageIntensity: "enterprise",
      enterpriseFocused: true,
      description:
        "Enterprise Copilot plan for larger organizations needing knowledge integration, policy controls, and enterprise governance.",
    },
  ],
} satisfies Record<PricedAuditTool, PlanMetadata[]>;

export function isPricedTool(tool: string): tool is PricedAuditTool {
  return tool in pricingMetadata;
}

export function getPlansForTool(tool: string): PlanMetadata[] {
  return isPricedTool(tool) ? pricingMetadata[tool] : [];
}

export function findPlan(tool: string, planName: string): PlanMetadata | undefined {
  const normalizedPlan = planName.toLowerCase();

  return getPlansForTool(tool).find(
    (plan) =>
      plan.planName.toLowerCase() === normalizedPlan ||
      (normalizedPlan === "individual" && plan.planName === "Pro") ||
      (tool === "Cursor" && normalizedPlan === "business" && plan.planName === "Teams") ||
      (tool === "ChatGPT" && normalizedPlan === "team" && plan.planName === "Business"),
  );
}
